[browser]
gatherUsageStats = false

[client]
toolbarMode = "viewer"
showSidebarNavigation = false

[server]
headless = true

[ui]
hideTopBar = true

[theme]
base = "light"
primaryColor = "#0B4F6C"
backgroundColor = "#F7FBFC"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1A2B33"
font = "sans serif"
